idf_component_register(
    SRCS
        "main.cpp"
        "voice_activation.cpp"
        "espnow_master.cpp"
        "swarm_link.cpp"
        "swarm_display.cpp"

    INCLUDE_DIRS
        "."

    REQUIRES
    esp_http_client
        esp32-camera
        edge_impulse_sdk
        nvs_flash
        esp_wifi
        esp_http_server
        esp_pm
        esp_timer
        spiffs
        human_face_detect
        human_face_recognition
        esp-dl
        esp-sr
        esp_codec_dev
        heap
        esp32_s3_eye
        esp_lvgl_port
        lvgl
)

component_compile_options(
    -O3
    -ffast-math
    -mlongcalls
    -Wno-error=cpp
    -Wno-error=missing-field-initializers
    -Wno-missing-field-initializers
    -Wno-error=uninitialized
    -Wno-error=maybe-uninitialized
    -Wno-uninitialized
    -Wno-maybe-uninitialized
    -Wno-deprecated-declarations
)